dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
script: mvn test -Dspring-boot.run.profiles=mysql-travis
addons:
  sonarcloud:
    organization: "gii-is-dp1" # the key of the org you chose at step #3
    token:
      secure: "*********" # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo
