package org.springframework.samples.petclinic.service.exceptions;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link DuplicatedCircuitoNameException} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractDuplicatedCircuitoNameExceptionAssert<S extends AbstractDuplicatedCircuitoNameExceptionAssert<S, A>, A extends DuplicatedCircuitoNameException> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractDuplicatedCircuitoNameExceptionAssert}</code> to make assertions on actual DuplicatedCircuitoNameException.
   * @param actual the DuplicatedCircuitoNameException we want to make assertions on.
   */
  protected AbstractDuplicatedCircuitoNameExceptionAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
