package org.springframework.samples.petclinic.service.exceptions;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link DuplicatedSalaNameException} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractDuplicatedSalaNameExceptionAssert<S extends AbstractDuplicatedSalaNameExceptionAssert<S, A>, A extends DuplicatedSalaNameException> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractDuplicatedSalaNameExceptionAssert}</code> to make assertions on actual DuplicatedSalaNameException.
   * @param actual the DuplicatedSalaNameException we want to make assertions on.
   */
  protected AbstractDuplicatedSalaNameExceptionAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
