package org.springframework.samples.petclinic.service.exceptions;

/**
 * {@link DuplicatedSalaNameException} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractDuplicatedSalaNameExceptionAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class DuplicatedSalaNameExceptionAssert extends AbstractDuplicatedSalaNameExceptionAssert<DuplicatedSalaNameExceptionAssert, DuplicatedSalaNameException> {

  /**
   * Creates a new <code>{@link DuplicatedSalaNameExceptionAssert}</code> to make assertions on actual DuplicatedSalaNameException.
   * @param actual the DuplicatedSalaNameException we want to make assertions on.
   */
  public DuplicatedSalaNameExceptionAssert(DuplicatedSalaNameException actual) {
    super(actual, DuplicatedSalaNameExceptionAssert.class);
  }

  /**
   * An entry point for DuplicatedSalaNameExceptionAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myDuplicatedSalaNameException)</code> and get specific assertion with code completion.
   * @param actual the DuplicatedSalaNameException we want to make assertions on.
   * @return a new <code>{@link DuplicatedSalaNameExceptionAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static DuplicatedSalaNameExceptionAssert assertThat(DuplicatedSalaNameException actual) {
    return new DuplicatedSalaNameExceptionAssert(actual);
  }
}
