package org.springframework.samples.petclinic.service.exceptions;

/**
 * {@link DuplicatedCircuitoNameException} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractDuplicatedCircuitoNameExceptionAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class DuplicatedCircuitoNameExceptionAssert extends AbstractDuplicatedCircuitoNameExceptionAssert<DuplicatedCircuitoNameExceptionAssert, DuplicatedCircuitoNameException> {

  /**
   * Creates a new <code>{@link DuplicatedCircuitoNameExceptionAssert}</code> to make assertions on actual DuplicatedCircuitoNameException.
   * @param actual the DuplicatedCircuitoNameException we want to make assertions on.
   */
  public DuplicatedCircuitoNameExceptionAssert(DuplicatedCircuitoNameException actual) {
    super(actual, DuplicatedCircuitoNameExceptionAssert.class);
  }

  /**
   * An entry point for DuplicatedCircuitoNameExceptionAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myDuplicatedCircuitoNameException)</code> and get specific assertion with code completion.
   * @param actual the DuplicatedCircuitoNameException we want to make assertions on.
   * @return a new <code>{@link DuplicatedCircuitoNameExceptionAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static DuplicatedCircuitoNameExceptionAssert assertThat(DuplicatedCircuitoNameException actual) {
    return new DuplicatedCircuitoNameExceptionAssert(actual);
  }
}
