package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link AdminMockTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractAdminMockTestAssert<S extends AbstractAdminMockTestAssert<S, A>, A extends AdminMockTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractAdminMockTestAssert}</code> to make assertions on actual AdminMockTest.
   * @param actual the AdminMockTest we want to make assertions on.
   */
  protected AbstractAdminMockTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
