package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link HorarioMockedServiceTests} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractHorarioMockedServiceTestsAssert<S extends AbstractHorarioMockedServiceTestsAssert<S, A>, A extends HorarioMockedServiceTests> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractHorarioMockedServiceTestsAssert}</code> to make assertions on actual HorarioMockedServiceTests.
   * @param actual the HorarioMockedServiceTests we want to make assertions on.
   */
  protected AbstractHorarioMockedServiceTestsAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
