package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link UserMockTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractUserMockTestAssert<S extends AbstractUserMockTestAssert<S, A>, A extends UserMockTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractUserMockTestAssert}</code> to make assertions on actual UserMockTest.
   * @param actual the UserMockTest we want to make assertions on.
   */
  protected AbstractUserMockTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
