package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link CitaService} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractCitaServiceAssert<S extends AbstractCitaServiceAssert<S, A>, A extends CitaService> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractCitaServiceAssert}</code> to make assertions on actual CitaService.
   * @param actual the CitaService we want to make assertions on.
   */
  protected AbstractCitaServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
