package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link BalanceMockTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractBalanceMockTestAssert<S extends AbstractBalanceMockTestAssert<S, A>, A extends BalanceMockTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractBalanceMockTestAssert}</code> to make assertions on actual BalanceMockTest.
   * @param actual the BalanceMockTest we want to make assertions on.
   */
  protected AbstractBalanceMockTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
