package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link AuthoritiesService} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractAuthoritiesServiceAssert<S extends AbstractAuthoritiesServiceAssert<S, A>, A extends AuthoritiesService> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractAuthoritiesServiceAssert}</code> to make assertions on actual AuthoritiesService.
   * @param actual the AuthoritiesService we want to make assertions on.
   */
  protected AbstractAuthoritiesServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
