package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link AdminService} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractAdminServiceAssert<S extends AbstractAdminServiceAssert<S, A>, A extends AdminService> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractAdminServiceAssert}</code> to make assertions on actual AdminService.
   * @param actual the AdminService we want to make assertions on.
   */
  protected AbstractAdminServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
