package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link EmployeeMockTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractEmployeeMockTestAssert<S extends AbstractEmployeeMockTestAssert<S, A>, A extends EmployeeMockTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractEmployeeMockTestAssert}</code> to make assertions on actual EmployeeMockTest.
   * @param actual the EmployeeMockTest we want to make assertions on.
   */
  protected AbstractEmployeeMockTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
