package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link EmailMockTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractEmailMockTestAssert<S extends AbstractEmailMockTestAssert<S, A>, A extends EmailMockTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractEmailMockTestAssert}</code> to make assertions on actual EmailMockTest.
   * @param actual the EmailMockTest we want to make assertions on.
   */
  protected AbstractEmailMockTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
