package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link TokenMockTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractTokenMockTestAssert<S extends AbstractTokenMockTestAssert<S, A>, A extends TokenMockTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractTokenMockTestAssert}</code> to make assertions on actual TokenMockTest.
   * @param actual the TokenMockTest we want to make assertions on.
   */
  protected AbstractTokenMockTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
