package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link CircuitMockTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractCircuitMockTestAssert<S extends AbstractCircuitMockTestAssert<S, A>, A extends CircuitMockTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractCircuitMockTestAssert}</code> to make assertions on actual CircuitMockTest.
   * @param actual the CircuitMockTest we want to make assertions on.
   */
  protected AbstractCircuitMockTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
