package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link HorarioService} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractHorarioServiceAssert<S extends AbstractHorarioServiceAssert<S, A>, A extends HorarioService> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractHorarioServiceAssert}</code> to make assertions on actual HorarioService.
   * @param actual the HorarioService we want to make assertions on.
   */
  protected AbstractHorarioServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
