package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link ClientMockTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractClientMockTestAssert<S extends AbstractClientMockTestAssert<S, A>, A extends ClientMockTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractClientMockTestAssert}</code> to make assertions on actual ClientMockTest.
   * @param actual the ClientMockTest we want to make assertions on.
   */
  protected AbstractClientMockTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
