package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link CitaMockedServiceTests} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractCitaMockedServiceTestsAssert<S extends AbstractCitaMockedServiceTestsAssert<S, A>, A extends CitaMockedServiceTests> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractCitaMockedServiceTestsAssert}</code> to make assertions on actual CitaMockedServiceTests.
   * @param actual the CitaMockedServiceTests we want to make assertions on.
   */
  protected AbstractCitaMockedServiceTestsAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
