package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link RoomMockTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractRoomMockTestAssert<S extends AbstractRoomMockTestAssert<S, A>, A extends RoomMockTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractRoomMockTestAssert}</code> to make assertions on actual RoomMockTest.
   * @param actual the RoomMockTest we want to make assertions on.
   */
  protected AbstractRoomMockTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
