package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link ClienteService} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractClienteServiceAssert<S extends AbstractClienteServiceAssert<S, A>, A extends ClienteService> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractClienteServiceAssert}</code> to make assertions on actual ClienteService.
   * @param actual the ClienteService we want to make assertions on.
   */
  protected AbstractClienteServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
