package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link BonoService} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractBonoServiceAssert<S extends AbstractBonoServiceAssert<S, A>, A extends BonoService> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractBonoServiceAssert}</code> to make assertions on actual BonoService.
   * @param actual the BonoService we want to make assertions on.
   */
  protected AbstractBonoServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
