package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link EmployeeService} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractEmployeeServiceAssert<S extends AbstractEmployeeServiceAssert<S, A>, A extends EmployeeService> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractEmployeeServiceAssert}</code> to make assertions on actual EmployeeService.
   * @param actual the EmployeeService we want to make assertions on.
   */
  protected AbstractEmployeeServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
