package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link UserService} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractUserServiceAssert<S extends AbstractUserServiceAssert<S, A>, A extends UserService> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractUserServiceAssert}</code> to make assertions on actual UserService.
   * @param actual the UserService we want to make assertions on.
   */
  protected AbstractUserServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
