package org.springframework.samples.petclinic.service;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link EmailService} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractEmailServiceAssert<S extends AbstractEmailServiceAssert<S, A>, A extends EmailService> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractEmailServiceAssert}</code> to make assertions on actual EmailService.
   * @param actual the EmailService we want to make assertions on.
   */
  protected AbstractEmailServiceAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
