package org.springframework.samples.petclinic.service;

/**
 * {@link AdminService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractAdminServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class AdminServiceAssert extends AbstractAdminServiceAssert<AdminServiceAssert, AdminService> {

  /**
   * Creates a new <code>{@link AdminServiceAssert}</code> to make assertions on actual AdminService.
   * @param actual the AdminService we want to make assertions on.
   */
  public AdminServiceAssert(AdminService actual) {
    super(actual, AdminServiceAssert.class);
  }

  /**
   * An entry point for AdminServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAdminService)</code> and get specific assertion with code completion.
   * @param actual the AdminService we want to make assertions on.
   * @return a new <code>{@link AdminServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static AdminServiceAssert assertThat(AdminService actual) {
    return new AdminServiceAssert(actual);
  }
}
