package org.springframework.samples.petclinic.service;

/**
 * {@link AdminMockTest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractAdminMockTestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class AdminMockTestAssert extends AbstractAdminMockTestAssert<AdminMockTestAssert, AdminMockTest> {

  /**
   * Creates a new <code>{@link AdminMockTestAssert}</code> to make assertions on actual AdminMockTest.
   * @param actual the AdminMockTest we want to make assertions on.
   */
  public AdminMockTestAssert(AdminMockTest actual) {
    super(actual, AdminMockTestAssert.class);
  }

  /**
   * An entry point for AdminMockTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAdminMockTest)</code> and get specific assertion with code completion.
   * @param actual the AdminMockTest we want to make assertions on.
   * @return a new <code>{@link AdminMockTestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static AdminMockTestAssert assertThat(AdminMockTest actual) {
    return new AdminMockTestAssert(actual);
  }
}
