package org.springframework.samples.petclinic.service;

/**
 * {@link AuthoritiesService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractAuthoritiesServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class AuthoritiesServiceAssert extends AbstractAuthoritiesServiceAssert<AuthoritiesServiceAssert, AuthoritiesService> {

  /**
   * Creates a new <code>{@link AuthoritiesServiceAssert}</code> to make assertions on actual AuthoritiesService.
   * @param actual the AuthoritiesService we want to make assertions on.
   */
  public AuthoritiesServiceAssert(AuthoritiesService actual) {
    super(actual, AuthoritiesServiceAssert.class);
  }

  /**
   * An entry point for AuthoritiesServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAuthoritiesService)</code> and get specific assertion with code completion.
   * @param actual the AuthoritiesService we want to make assertions on.
   * @return a new <code>{@link AuthoritiesServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static AuthoritiesServiceAssert assertThat(AuthoritiesService actual) {
    return new AuthoritiesServiceAssert(actual);
  }
}
