package org.springframework.samples.petclinic.service;

/**
 * {@link BalanceService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractBalanceServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class BalanceServiceAssert extends AbstractBalanceServiceAssert<BalanceServiceAssert, BalanceService> {

  /**
   * Creates a new <code>{@link BalanceServiceAssert}</code> to make assertions on actual BalanceService.
   * @param actual the BalanceService we want to make assertions on.
   */
  public BalanceServiceAssert(BalanceService actual) {
    super(actual, BalanceServiceAssert.class);
  }

  /**
   * An entry point for BalanceServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myBalanceService)</code> and get specific assertion with code completion.
   * @param actual the BalanceService we want to make assertions on.
   * @return a new <code>{@link BalanceServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static BalanceServiceAssert assertThat(BalanceService actual) {
    return new BalanceServiceAssert(actual);
  }
}
