package org.springframework.samples.petclinic.service;

/**
 * {@link BalanceMockTest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractBalanceMockTestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class BalanceMockTestAssert extends AbstractBalanceMockTestAssert<BalanceMockTestAssert, BalanceMockTest> {

  /**
   * Creates a new <code>{@link BalanceMockTestAssert}</code> to make assertions on actual BalanceMockTest.
   * @param actual the BalanceMockTest we want to make assertions on.
   */
  public BalanceMockTestAssert(BalanceMockTest actual) {
    super(actual, BalanceMockTestAssert.class);
  }

  /**
   * An entry point for BalanceMockTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myBalanceMockTest)</code> and get specific assertion with code completion.
   * @param actual the BalanceMockTest we want to make assertions on.
   * @return a new <code>{@link BalanceMockTestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static BalanceMockTestAssert assertThat(BalanceMockTest actual) {
    return new BalanceMockTestAssert(actual);
  }
}
