package org.springframework.samples.petclinic.service;

/**
 * {@link BonoService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractBonoServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class BonoServiceAssert extends AbstractBonoServiceAssert<BonoServiceAssert, BonoService> {

  /**
   * Creates a new <code>{@link BonoServiceAssert}</code> to make assertions on actual BonoService.
   * @param actual the BonoService we want to make assertions on.
   */
  public BonoServiceAssert(BonoService actual) {
    super(actual, BonoServiceAssert.class);
  }

  /**
   * An entry point for BonoServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myBonoService)</code> and get specific assertion with code completion.
   * @param actual the BonoService we want to make assertions on.
   * @return a new <code>{@link BonoServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static BonoServiceAssert assertThat(BonoService actual) {
    return new BonoServiceAssert(actual);
  }
}
