package org.springframework.samples.petclinic.service;

/**
 * {@link CircuitoService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractCircuitoServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class CircuitoServiceAssert extends AbstractCircuitoServiceAssert<CircuitoServiceAssert, CircuitoService> {

  /**
   * Creates a new <code>{@link CircuitoServiceAssert}</code> to make assertions on actual CircuitoService.
   * @param actual the CircuitoService we want to make assertions on.
   */
  public CircuitoServiceAssert(CircuitoService actual) {
    super(actual, CircuitoServiceAssert.class);
  }

  /**
   * An entry point for CircuitoServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myCircuitoService)</code> and get specific assertion with code completion.
   * @param actual the CircuitoService we want to make assertions on.
   * @return a new <code>{@link CircuitoServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static CircuitoServiceAssert assertThat(CircuitoService actual) {
    return new CircuitoServiceAssert(actual);
  }
}
