package org.springframework.samples.petclinic.service;

/**
 * {@link CircuitMockTest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractCircuitMockTestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class CircuitMockTestAssert extends AbstractCircuitMockTestAssert<CircuitMockTestAssert, CircuitMockTest> {

  /**
   * Creates a new <code>{@link CircuitMockTestAssert}</code> to make assertions on actual CircuitMockTest.
   * @param actual the CircuitMockTest we want to make assertions on.
   */
  public CircuitMockTestAssert(CircuitMockTest actual) {
    super(actual, CircuitMockTestAssert.class);
  }

  /**
   * An entry point for CircuitMockTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myCircuitMockTest)</code> and get specific assertion with code completion.
   * @param actual the CircuitMockTest we want to make assertions on.
   * @return a new <code>{@link CircuitMockTestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static CircuitMockTestAssert assertThat(CircuitMockTest actual) {
    return new CircuitMockTestAssert(actual);
  }
}
