package org.springframework.samples.petclinic.service;

/**
 * {@link CitaService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractCitaServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class CitaServiceAssert extends AbstractCitaServiceAssert<CitaServiceAssert, CitaService> {

  /**
   * Creates a new <code>{@link CitaServiceAssert}</code> to make assertions on actual CitaService.
   * @param actual the CitaService we want to make assertions on.
   */
  public CitaServiceAssert(CitaService actual) {
    super(actual, CitaServiceAssert.class);
  }

  /**
   * An entry point for CitaServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myCitaService)</code> and get specific assertion with code completion.
   * @param actual the CitaService we want to make assertions on.
   * @return a new <code>{@link CitaServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static CitaServiceAssert assertThat(CitaService actual) {
    return new CitaServiceAssert(actual);
  }
}
