package org.springframework.samples.petclinic.service;

/**
 * {@link CitaMockedServiceTests} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractCitaMockedServiceTestsAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class CitaMockedServiceTestsAssert extends AbstractCitaMockedServiceTestsAssert<CitaMockedServiceTestsAssert, CitaMockedServiceTests> {

  /**
   * Creates a new <code>{@link CitaMockedServiceTestsAssert}</code> to make assertions on actual CitaMockedServiceTests.
   * @param actual the CitaMockedServiceTests we want to make assertions on.
   */
  public CitaMockedServiceTestsAssert(CitaMockedServiceTests actual) {
    super(actual, CitaMockedServiceTestsAssert.class);
  }

  /**
   * An entry point for CitaMockedServiceTestsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myCitaMockedServiceTests)</code> and get specific assertion with code completion.
   * @param actual the CitaMockedServiceTests we want to make assertions on.
   * @return a new <code>{@link CitaMockedServiceTestsAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static CitaMockedServiceTestsAssert assertThat(CitaMockedServiceTests actual) {
    return new CitaMockedServiceTestsAssert(actual);
  }
}
