package org.springframework.samples.petclinic.service;

/**
 * {@link ClientMockTest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractClientMockTestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ClientMockTestAssert extends AbstractClientMockTestAssert<ClientMockTestAssert, ClientMockTest> {

  /**
   * Creates a new <code>{@link ClientMockTestAssert}</code> to make assertions on actual ClientMockTest.
   * @param actual the ClientMockTest we want to make assertions on.
   */
  public ClientMockTestAssert(ClientMockTest actual) {
    super(actual, ClientMockTestAssert.class);
  }

  /**
   * An entry point for ClientMockTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myClientMockTest)</code> and get specific assertion with code completion.
   * @param actual the ClientMockTest we want to make assertions on.
   * @return a new <code>{@link ClientMockTestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ClientMockTestAssert assertThat(ClientMockTest actual) {
    return new ClientMockTestAssert(actual);
  }
}
