package org.springframework.samples.petclinic.service;

/**
 * {@link EmailService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractEmailServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class EmailServiceAssert extends AbstractEmailServiceAssert<EmailServiceAssert, EmailService> {

  /**
   * Creates a new <code>{@link EmailServiceAssert}</code> to make assertions on actual EmailService.
   * @param actual the EmailService we want to make assertions on.
   */
  public EmailServiceAssert(EmailService actual) {
    super(actual, EmailServiceAssert.class);
  }

  /**
   * An entry point for EmailServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myEmailService)</code> and get specific assertion with code completion.
   * @param actual the EmailService we want to make assertions on.
   * @return a new <code>{@link EmailServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static EmailServiceAssert assertThat(EmailService actual) {
    return new EmailServiceAssert(actual);
  }
}
