package org.springframework.samples.petclinic.service;

/**
 * {@link EmployeeService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractEmployeeServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class EmployeeServiceAssert extends AbstractEmployeeServiceAssert<EmployeeServiceAssert, EmployeeService> {

  /**
   * Creates a new <code>{@link EmployeeServiceAssert}</code> to make assertions on actual EmployeeService.
   * @param actual the EmployeeService we want to make assertions on.
   */
  public EmployeeServiceAssert(EmployeeService actual) {
    super(actual, EmployeeServiceAssert.class);
  }

  /**
   * An entry point for EmployeeServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myEmployeeService)</code> and get specific assertion with code completion.
   * @param actual the EmployeeService we want to make assertions on.
   * @return a new <code>{@link EmployeeServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static EmployeeServiceAssert assertThat(EmployeeService actual) {
    return new EmployeeServiceAssert(actual);
  }
}
