package org.springframework.samples.petclinic.service;

/**
 * {@link HorarioMockedServiceTests} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractHorarioMockedServiceTestsAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class HorarioMockedServiceTestsAssert extends AbstractHorarioMockedServiceTestsAssert<HorarioMockedServiceTestsAssert, HorarioMockedServiceTests> {

  /**
   * Creates a new <code>{@link HorarioMockedServiceTestsAssert}</code> to make assertions on actual HorarioMockedServiceTests.
   * @param actual the HorarioMockedServiceTests we want to make assertions on.
   */
  public HorarioMockedServiceTestsAssert(HorarioMockedServiceTests actual) {
    super(actual, HorarioMockedServiceTestsAssert.class);
  }

  /**
   * An entry point for HorarioMockedServiceTestsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myHorarioMockedServiceTests)</code> and get specific assertion with code completion.
   * @param actual the HorarioMockedServiceTests we want to make assertions on.
   * @return a new <code>{@link HorarioMockedServiceTestsAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static HorarioMockedServiceTestsAssert assertThat(HorarioMockedServiceTests actual) {
    return new HorarioMockedServiceTestsAssert(actual);
  }
}
