package org.springframework.samples.petclinic.service;

/**
 * {@link HorarioService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractHorarioServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class HorarioServiceAssert extends AbstractHorarioServiceAssert<HorarioServiceAssert, HorarioService> {

  /**
   * Creates a new <code>{@link HorarioServiceAssert}</code> to make assertions on actual HorarioService.
   * @param actual the HorarioService we want to make assertions on.
   */
  public HorarioServiceAssert(HorarioService actual) {
    super(actual, HorarioServiceAssert.class);
  }

  /**
   * An entry point for HorarioServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myHorarioService)</code> and get specific assertion with code completion.
   * @param actual the HorarioService we want to make assertions on.
   * @return a new <code>{@link HorarioServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static HorarioServiceAssert assertThat(HorarioService actual) {
    return new HorarioServiceAssert(actual);
  }
}
