package org.springframework.samples.petclinic.service;

/**
 * {@link RoomMockTest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRoomMockTestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RoomMockTestAssert extends AbstractRoomMockTestAssert<RoomMockTestAssert, RoomMockTest> {

  /**
   * Creates a new <code>{@link RoomMockTestAssert}</code> to make assertions on actual RoomMockTest.
   * @param actual the RoomMockTest we want to make assertions on.
   */
  public RoomMockTestAssert(RoomMockTest actual) {
    super(actual, RoomMockTestAssert.class);
  }

  /**
   * An entry point for RoomMockTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRoomMockTest)</code> and get specific assertion with code completion.
   * @param actual the RoomMockTest we want to make assertions on.
   * @return a new <code>{@link RoomMockTestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RoomMockTestAssert assertThat(RoomMockTest actual) {
    return new RoomMockTestAssert(actual);
  }
}
