package org.springframework.samples.petclinic.service;

/**
 * {@link SalaService} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractSalaServiceAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class SalaServiceAssert extends AbstractSalaServiceAssert<SalaServiceAssert, SalaService> {

  /**
   * Creates a new <code>{@link SalaServiceAssert}</code> to make assertions on actual SalaService.
   * @param actual the SalaService we want to make assertions on.
   */
  public SalaServiceAssert(SalaService actual) {
    super(actual, SalaServiceAssert.class);
  }

  /**
   * An entry point for SalaServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(mySalaService)</code> and get specific assertion with code completion.
   * @param actual the SalaService we want to make assertions on.
   * @return a new <code>{@link SalaServiceAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static SalaServiceAssert assertThat(SalaService actual) {
    return new SalaServiceAssert(actual);
  }
}
