package org.springframework.samples.petclinic.service;

/**
 * {@link TokenMockTest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTokenMockTestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TokenMockTestAssert extends AbstractTokenMockTestAssert<TokenMockTestAssert, TokenMockTest> {

  /**
   * Creates a new <code>{@link TokenMockTestAssert}</code> to make assertions on actual TokenMockTest.
   * @param actual the TokenMockTest we want to make assertions on.
   */
  public TokenMockTestAssert(TokenMockTest actual) {
    super(actual, TokenMockTestAssert.class);
  }

  /**
   * An entry point for TokenMockTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTokenMockTest)</code> and get specific assertion with code completion.
   * @param actual the TokenMockTest we want to make assertions on.
   * @return a new <code>{@link TokenMockTestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TokenMockTestAssert assertThat(TokenMockTest actual) {
    return new TokenMockTestAssert(actual);
  }
}
