package org.springframework.samples.petclinic.service;

/**
 * {@link UserMockTest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractUserMockTestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class UserMockTestAssert extends AbstractUserMockTestAssert<UserMockTestAssert, UserMockTest> {

  /**
   * Creates a new <code>{@link UserMockTestAssert}</code> to make assertions on actual UserMockTest.
   * @param actual the UserMockTest we want to make assertions on.
   */
  public UserMockTestAssert(UserMockTest actual) {
    super(actual, UserMockTestAssert.class);
  }

  /**
   * An entry point for UserMockTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myUserMockTest)</code> and get specific assertion with code completion.
   * @param actual the UserMockTest we want to make assertions on.
   * @return a new <code>{@link UserMockTestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserMockTestAssert assertThat(UserMockTest actual) {
    return new UserMockTestAssert(actual);
  }
}
